theme: jekyll-theme-minimal
logo: assets/img/logo.png
show_downloads: true
title: "Gregor's fun with PHP"
lang: de-AT
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: false
